package workoutPlanner.dataObjects.enums;

public enum ExerciseNames {
	LUMBERJACK_SQUAT_TO_PRESS,
	HACKSQUAT,
	MEADOWS_ROW,
	INVERTED_ROW,
	INCLINE_BENCH_PRESS,
	RDL,
	REVERSE_LUNGE,
	PULLUPS,
	DIP,
	PEC_FLY,
	BICEP_CURL,
	LATERAL_RAISE,
	SHOULDER_PRESS,
	REAR_DELT_FLY,
	LEG_CURLS,
	LEG_EXTENSIONS,
	CHEST_SUPPORTED_ROW,
	PLANK,
	SIDE_PLANK,
	OVERHEAD_TRICEP_EXTENSION,
	SKULLCRUSHER,
	Y_RAISE,
	CANDLESTICK,
	DEADLIFT
}
